apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: 061051242980.dkr.ecr.us-east-1.amazonaws.com/monitoring-app:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-credentials